title: My new course
description: New course 2
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
    link: firststeplink.com
    title: First Step
    video: firststepvideolink.com
  - title: New step
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
    course: Step 2
    description: Description of a new step
    link: linkefornewcourse.com
    video: videolink.com
